steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_world
  - --region=asia-south1
  - --source=.
  - --trigger-http
  - --runtime=python37
  dir: 'cloudfunction'
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['install']
  dir: 'cloudrun/angular'
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['run','build']
  dir: 'cloudrun/angular'  
 # Build the container image
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '-t', 'gcr.io/cloudbuild-training/cloudbuildtest:$COMMIT_SHA', '.']
  dir: 'cloudrun'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '--image', 'gcr.io/cloudbuild-training/cloudbuildtest:$COMMIT_SHA']
  dir: 'cloudrun'
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'cloudbuildtest'
  - '--image'
  - 'gcr.io/cloudbuild-training/cloudbuildtest:$COMMIT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
  dir: 'cloudrun'
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['install']
  dir: 'website/angular'
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['run','build']
  dir: 'website/angular'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['-q','app', 'deploy', 'app.yaml']
  dir: 'website'
images:
- 'gcr.io/cloudbuild-training/cloudbuildtest:$COMMIT_SHA'

timeout: 1200s