steps:
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['run','build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['-q','app', 'deploy', 'app.yaml']