steps:
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['install']
  dir: 'angular'
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['run','build']
  dir: 'angular'  
 # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloudbuild-training/cloudbuildtest:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloudbuild-training/cloudbuildtest:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'cloudbuildtest'
  - '--image'
  - 'gcr.io/cloudbuild-training/cloudbuildtest:$COMMIT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/cloudbuild-training/cloudbuildtest:$COMMIT_SHA'
