steps:
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['install']
  dir: 'dummy-website/angular'
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['run','build']
  dir: 'dummy-website/angular'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['-q','app', 'deploy', 'app.yaml']
  dir: 'dummy-website'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - practice-cloudbuild
  - --region=asia-south1
  - --source=.
  - --trigger-http
  - --runtime=python37
  dir: 'dummy-cloudfunction'

 # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fast-ability-317910/cloudbuildtest:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/fast-ability-317910/cloudbuildtest:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'SERVICE-NAME'
  - '--image'
  - 'gcr.io/fast-ability-317910/cloudbuildtest:$COMMIT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/fast-ability-317910/cloudbuildtest:$COMMIT_SHA'